
\ NVIC. Written by hand. TODO somewhat incomplete.

bits only definitions

_reg voc: NVIC

: _msk ( nr -- mask offset )
  dup 3 rshift $3 bic swap $1F and 1 swap lshift
  1-foldable
;

\ Interrupt Set Enable
\ Write: enable this interrupt
\ Read: is this interrupt enabled?

voc: _rflg

: @ ( mask offset -- flag )
  bit@ ;

previous definitions

_rflg voc: _flg

: +! ( mask offset -- )
  ! ;

: -! ( mask offset -- )
  $80 + ! ;

previous definitions

_flg item
: enabled ( n -- mask offset )
  _msk $E000E100 +
;

_flg item
: pending ( n -- mask offset )
  _msk $E000E200 +
;

_rflg item
: active ( n -- flag )
  _msk $E000E300 + 
;

\ Interrupt Priority Register
\ IRQ number must be ≥ 0

var> cint item
: prio ( nr -- addr )
  $E000E400 + ;


\ System Handler Priority Registers
\ IRQ number must be [-12…-1]

var> cint item
: shpr ( nr -- addr )
  12 $E000ED18 + + ;

\ AIARC: App Interrupt And Reset Control
  &rg voc: _AIARC
        &bf item \ 31:16
    $210 constant VECTKEY \ key field for writing
        &bi item \ 15
    $F constant ENDIANESS \ Enable SysTick Timer
        &bf item \ 10:8
    $68 constant PRIGROUP \ key field for writing
        &bi item \ 2
    $2 constant SYSRESETREQ \ assert external reset
        &bi item \ 1
    $1 constant VECTCLRACTIVE
        &bi item \ 0
    $0 constant VECTRESET

    $05FA constant MAGIC
        previous definitions
  _AIARC item
$E000ED0C constant AIARC

\ SHCSR: System Handler Control and State Register
  &rg voc: _SHCSR
        &bi item \ 18
    $12 constant USGFAULTENA
        &bi item \ 17
    $11 constant BUSFAULTENA
        &bi item \ 16
    $10 constant MEMFAULTENA
        &bi item \ 15
    $F constant SVCALLPENDED
        &bi item \ 14
    $E constant BUSFAULTPENDED
        &bi item \ 13
    $D constant MEMFAULTPENDED
        &bi item \ 12
    $C constant USGFAULTPENDED
        &bi item \ 11
    $B constant SYSTICKACT
        &bi item \ 10
    $A constant PENDSVACT
        &bi item \ 8
    $8 constant MONITORACT
        &bi item \ 7
    $7 constant SVCALLACT
        &bi item \ 3
    $3 constant USGFAULTACT
        &bi item \ 1
    $1 constant BUSFAULTACT
        &bi item \ 0
    $0 constant MEMFAULTACT
        previous definitions
  _SHCSR item
$E000ED24 constant SHCSR


\ ICSR: Interrut Control State Register
  &rg voc: _ICSR
        &bi item \ 31
    $1F constant NMIPENDSET
        &bi item \ 28
    $1C constant PENDSVSET
        &bi item \ 27
    $1B constant PENDSVCLR
        &bi item \ 26
    $1A constant PENDSTSET
        &bi item \ 25
    $19 constant PENDSTCLR
        &bi item \ 23
    $17 constant ISRPREEMPT
        &bi item \ 22
    $16 constant ISRPENDING
        &bf item \ 12:21
    $14C constant VECTPENDING
        &bi item \ 11
    $0B constant RETTOBASE
        &bf item \ 8:0
    $100 constant VECTACTIVE

        previous definitions
  _ICSR item
$E000ED04 constant ICSR

voc: irq
-14 constant  NMI
-13 constant  HardFault
-12 constant  MemMgr
-11 constant  BusFault
-10 constant  UsageFault
-9 constant  SecureFault
-4 constant  SVCall
-3 constant  DebugMon
-2 constant  PendSV
-1 constant  SysTick


forth definitions
#ok depth 0=

\ This file is auto-generated by "mapgen", part of MoaT Forth.
\ The generator states:
\ SPDX-License-Identifier: GPL-3.0-only
\ 
\ EOF

