#!/usr/bin/python

import sys
from itertools import combinations
words = sys.argv[1:]

print("")
def out(r):
    print("-F "+" -F ".join(r))

for n in range(1,len(words)):
    for x in combinations(words,n):
        out(x)
out(words)
