#!/bin/bash
set -eu

DEV="$1"
ARCH=$2
VENDOR=$3
MCU=$4
CLK=$5

F="" # no variants, for now

trap 'echo "ERROR $FLG"; exit 1' ERR

while read FLG ; do

echo TEST $FLG

if ! env PYTHONPATH=. scripts/mf-term -x test/main.fs -F erase -F arch=$ARCH -F real=$VENDOR -F mcu=$MCU -F clock=$CLK $FLG  -b -q -g ok. "$DEV"
then
	env PYTHONPATH=. scripts/mf-term -x test/main.fs -F erase -F arch=$ARCH -F real=$VENDOR -F mcu=$MCU -F clock=$CLK $FLG -D -g ok. "$DEV" </dev/tty >/dev/tty 2>&1
	exit 1
fi

done < <(scripts/permute $F)

echo OK
