#!/bin/bash
set -eu

F="debug"

trap 'echo "ERROR $FLG"; exit 1' ERR

while read FLG ; do

echo TEST $FLG

PYTHONPATH=. scripts/mf-cmd -x test/main.fs  $FLG  -b -q -g ok. ../mecrisp-stellaris/linux-ra/mecrisp-stellaris-linux

done < <(scripts/permute $F)

echo OK
