#!/bin/bash
set -eu

MECRISP="${MECRISP:-../mecrisp-stellaris/linux-ra/mecrisp-stellaris-linux}"
F="debug multi"

trap 'echo "ERROR $FLG"; exit 1' ERR

while read FLG ; do

echo TEST $FLG

if ! scripts/mf-term -x test/main.fs  $FLG  -F machid=123456789 -b -q -g ok. -c "$MECRISP"
then
	scripts/mf-term -x test/main.fs  $FLG -F machid=123456789 -b -t /dev/tty -g ok. -c "$MECRISP"
	exit 1
fi

done < <(scripts/permute $F)

echo OK
