#!/bin/bash
set -eu

F="debug multi"

trap 'echo "ERROR $FLG"; exit 1' ERR

while read FLG ; do

echo TEST $FLG

if ! scripts/mf-term -x test/main.fs  $FLG  -F machid=123456789 -b -q -g ok. -c ../mecrisp-stellaris/linux-ra/mecrisp-stellaris-linux
then
	scripts/mf-term -x test/main.fs  $FLG -F machid=123456789 -D -g ok. -c ../mecrisp-stellaris/linux-ra/mecrisp-stellaris-linux </dev/tty >/dev/tty 2>&1
	exit 1
fi

done < <(scripts/permute $F)

echo OK
